-- Fix item_mapping and item_volumes tables to match the correct schema
-- This migration corrects the schema mismatch from 0005_complete_schema_sync.sql

-- Step 1: Drop foreign key constraints that depend on item_mapping
DO $$ 
BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'item_price_history') THEN
		ALTER TABLE "item_price_history" DROP CONSTRAINT IF EXISTS "item_price_history_item_id_item_mapping_id_fk";
	END IF;
END $$;

-- Step 2: Drop incorrect tables (CASCADE will handle dependent objects)
DROP TABLE IF EXISTS "item_mapping" CASCADE;
DROP TABLE IF EXISTS "item_volumes" CASCADE;

-- Step 3: Create item_mapping table with correct schema
CREATE TABLE "item_mapping" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"examine" text,
	"members" boolean DEFAULT false,
	"lowalch" integer,
	"highalch" integer,
	"limit" integer,
	"value" integer,
	"icon" text,
	"wiki_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

-- Step 4: Create item_volumes table with correct schema
CREATE TABLE "item_volumes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"item_id" integer NOT NULL,
	"high_price" integer,
	"low_price" integer,
	"high_price_volume" integer DEFAULT 0 NOT NULL,
	"low_price_volume" integer DEFAULT 0 NOT NULL,
	"hourly_high_price_volume" integer DEFAULT 0,
	"hourly_low_price_volume" integer DEFAULT 0,
	"last_updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "item_volumes_item_id_unique" UNIQUE("item_id")
);

-- Step 5: Recreate foreign key from item_price_history to item_mapping if item_price_history exists
DO $$ 
BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'item_price_history') THEN
		ALTER TABLE "item_price_history" ADD CONSTRAINT "item_price_history_item_id_item_mapping_id_fk" 
			FOREIGN KEY ("item_id") REFERENCES "public"."item_mapping"("id") ON DELETE no action ON UPDATE no action;
	END IF;
END $$;

